[project]
name = "pythonando"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "parsel>=1.10.0",
    "requests>=2.32.4",
    "tqdm>=4.67.1",
    "yt-dlp>=2025.6.9",
]
